[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP235x --protocol swd"
#runner = "/opt/picotool load -u -v -x -t elf"

#rustflags = [
#]

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
