[build]
target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
# Pass some extra options to rustc, some of which get passed on to the linker.
#
# * linker argument --nmagic turns off page alignment of sections (which saves
#   flash space)
# * linker argument -Trp235x_riscv.x also tells the linker to use
#   `rp235x_riscv.x` as a linker script. This adds in RP2350 RISC-V specific
#   things that the riscv-rt crate's `link.x` requires and then includes
#   `link.x` automatically. This is the reverse of how we do it on Cortex-M.
# * linker argument -Tdefmt.x also tells the linker to use `defmt.x` as a
#   secondary linker script. This is required to make defmt_rtt work.
rustflags = [
    "-C",
    "link-arg=--nmagic",
    "-C",
    "link-arg=-Tmemory.x",
    "-C",
    "link-arg=-Tdefmt.x",
]

# Use picotool for loading.
#
# Load an elf, skipping unchanged flash sectors, verify it, and execute it
runner = "/opt/picotool load -u -v -x -t elf"

[env]
DEFMT_LOG = "debug"
